[package]
name = "bike_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
# egui_extras = " { version = "0.22.0", features = ["image"] }"
egui_file = "0.9"
simplersble = "0.6.0"
